language: csharp
dist: bionic
sudo: required
mono: none
dotnet: 3.0
solution: RediSearchCore.sln
before_install:
  - docker pull redislabs/redisearch:latest
  - docker run -d -p 6379:6379 redislabs/redisearch:latest
script:
  - dotnet restore
  - dotnet build
  - dotnet test RediSearchCore.Tests/RediSearchCore.Tests.csproj